# Generated by Django 4.2.6 on 2023-10-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
