# Generated by Django 4.2.6 on 2023-10-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_react_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='time',
        ),
    ]
