# Generated by Django 4.2.6 on 2023-10-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_react_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
