# Generated by Django 4.2.6 on 2023-10-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_react_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=400)),
                ('todays_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
