# Generated by Django 4.2.6 on 2023-10-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_school_name_school_school_name_cus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_name_cus',
            new_name='school_name',
        ),
    ]
